Applied debdiff from Lucas' NMU
git-svn-id: svn://svn.debian.org/svn/pkg-openmpi/openmpi/trunk@211 73dcd3bc-d895-4a24-a01c-79f548e222e3

diff --git a/debian/openmpi-bin.postinst b/debian/openmpi-bin.postinst
--- a/debian/openmpi-bin.postinst
+++ b/debian/openmpi-bin.postinst
@@ -2,7 +2,26 @@
 
 set -e
 
-update-alternatives --quiet --remove-all mpiexec >/dev/null 2>&1 || true
+case "$1" in
+   configure)
+      # Continue below
+      ;;
+   abort-upgrade|abort-remove|abort-deconfigure)
+      exit 0;
+      ;;
+   *)
+      echo "postinst called with unknown argument \`$1'" >&2
+      exit 0;
+      ;;
+esac
+
+# so, we are running with $1 = configure
+# openmpi versions before 1.3.3-2 were using two alternatives where other
+# MPI implementations were using only one, which breaks. Clean up
+# our mess.
+if [ "$2" != "" ] && dpkg --compare-versions "$2" le "1.3.3-2"; then
+    update-alternatives --remove mpiexec /usr/bin/mpiexec.openmpi
+fi
 
 update-alternatives \
 	--install /usr/bin/mpirun mpirun /usr/bin/mpirun.openmpi 40 \
